version: '3.8'

services:
  nginx:
    image: nullisdefined/nanalmoa-nginx:latest
    container_name: nanalmoa-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - server
      - client

  client:
    image: nullisdefined/nanalmoa-client:latest
    container_name: nanalmoa-client
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./packages/client/dist:/usr/share/nginx/html

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    image: nullisdefined/nanalmoa-server:latest
    container_name: nanalmoa-server
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3333:3333"
    depends_on:
      - db
    env_file:
      - ./packages/server/.env

  db:
    image: postgres:15
    container_name: nanalmoa-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  certbot:
    image: certbot/certbot
    container_name: nanalmoa-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot --email admin@nanalmoa.site --agree-tos --no-eff-email --force-renewal -d nanalmoa.site -d www.nanalmoa.site"

volumes:
  pgdata: